"""Discover the set of *currently tradable* symbols for a market.

We only need one unauthenticated ``GET /exchangeInfo`` per run, so we call it
directly instead of pulling in the (now deprecated) ``binance-connector`` /
``binance-futures-connector`` packages.  This endpoint is the authoritative list
of live pairs, which lets the crawler skip delisted coins (e.g. ``0GUSDT``)
without a hand-maintained allow-list.

Quote asset per market:
  * spot            -> USDT, USDC, BTC, ...
  * um  (USDⓈ-M)    -> USDT (524 live perps) or USDC (38); "USDⓈ-M" == USD-margined,
                       it is the *product line*, not a single quote asset
  * cm  (COIN-M)    -> USD  (symbols look like BTCUSD_PERP), margined in the coin
"""

from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path

import requests

from .config import Config

LOG = logging.getLogger(__name__)

EXCHANGE_INFO_URL = {
    "spot": "https://api.binance.com/api/v3/exchangeInfo",
    "um": "https://fapi.binance.com/fapi/v1/exchangeInfo",
    "cm": "https://dapi.binance.com/dapi/v1/exchangeInfo",
}


def _exchange_info(cfg: Config) -> dict:
    """Raw ``exchangeInfo`` payload for the configured market."""
    url = cfg.base_api_url or EXCHANGE_INFO_URL[cfg.market]
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    return resp.json()


def _is_live(sym: dict, cfg: Config) -> bool:
    if sym.get("quoteAsset") != cfg.quote_asset:
        return False
    # spot + USDⓈ-M expose `status`; COIN-M exposes `contractStatus` instead
    if (sym.get("status") or sym.get("contractStatus")) != "TRADING":
        return False
    if cfg.market == "spot":
        return bool(sym.get("isSpotTradingAllowed", False))
    # futures: keep only perpetuals, drop dated (quarterly) contracts
    return sym.get("contractType") == "PERPETUAL"


def fetch_active_symbols(cfg: Config) -> list[str]:
    info = _exchange_info(cfg)
    symbols = sorted(
        {s["symbol"] for s in info.get("symbols", []) if _is_live(s, cfg)}
    )
    LOG.info(
        "exchangeInfo: %d live %s-quoted %s symbols",
        len(symbols),
        cfg.quote_asset,
        cfg.market,
    )
    return symbols


# ── symbols file IO ──────────────────────────────────────────────────────────
def write_symbols_file(path: str | Path, symbols: list[str], cfg: Config) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    header = [
        "# Auto-generated by `python -m binance_archive sync-symbols`.",
        f"# market={cfg.market} quote={cfg.quote_asset} generated={now}",
        f"# {len(symbols)} symbols - edit freely; lines starting with '#' are ignored.",
    ]
    p.write_text("\n".join(header + symbols) + "\n", encoding="utf-8")


def read_symbols_file(path: str | Path) -> list[str]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"symbols file {p} not found - run `python -m binance_archive sync-symbols` first"
        )
    out: list[str] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(line.upper())
    return out
